config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root to: 'games#index'
end

app/models/game.rb
class Game < ActiveRecord::Base
	validates :bundle_id, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!
	def index
		#@games = Game.all
		@tasks_grid = initialize_grid(Game)
		@total_games = Game.where(in_db: true).count
		@total_games_without_promo = Game.where(english_promo:"empty").where(in_db: true).count.to_f
		@total_games_without_square_banners = Game.where(square_banner:"empty").where(in_db: true).count.to_f
		@total_games_without_flat_banners = Game.where(flat_banner:"empty").where(in_db: true).count.to_f
		@total_games_without_video = Game.where(english_vid:"empty").where(in_db: true).count.to_f
	end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # You can put the params you want to permit in the empty array.
  def configure_sign_in_params
    devise_parameter_sanitizer.for(:sign_in) << :attribute
  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_grid.html.erb
<%= grid(@tasks_grid, upper_pagination_panel: true) do |g|

  g.column name:'In DB?', attribute:'in_db' do |task|
    task.in_db? ? 'Yes' : 'No'
  end

  g.column name: 'App name', attribute:'game_name' do |task|
    task.game_name
  end

  g.column name: 'Bundle_id', attribute:'bundle_id' do |task|
    task.bundle_id
  end

  g.column name: 'Platform', attribute:'platform', custom_filter: ['iOS', 'Android'] do |task|
    task.platform
  end

  g.column name:'Category', attribute:'category' do |task|
    task.category
  end

  g.column name: 'Promo', attribute:'english_promo' do |task|
      task.english_promo
  end

  g.column name: 'Landscape image', attribute:'landscape' do |task|
    if task.landscape != "empty"
      link_to 'See banner', task.landscape, :target => "_blank"
    else
      task.landscape
    end
  end

  g.column name: 'Portrait image', attribute:'portrait' do |task|
    if task.portrait != "empty"
      link_to 'See banner', task.portrait, :target => "_blank"
    else
      task.portrait
    end
  end

  g.column name:'300x250 banner', attribute:'square_banner' do |task|
    if task.square_banner != "empty"
      link_to 'See banner', task.square_banner, :target => "_blank"
    else
      task.square_banner
    end
  end

  g.column name:'320x50 banner', attribute:'flat_banner' do |task|
    if task.flat_banner != "empty"
      link_to 'See banner', task.flat_banner, :target => "_blank"
    else
      task.flat_banner
    end
  end

  g.column name:'video', attribute:'english_vid' do |task|
    if task.english_vid != "empty"
      link_to 'Watch video', task.english_vid, :target => "_blank"
    else
      task.english_vid
    end
  end    

end %>

app/views/games/index.html.erb
<nav class="navbar navbar-default navbar-fixed-top nav-dashboard">
  <div class="container">
    <div class="navbar-header">
      <%= image_tag("logo-apd-547a7dd01079245137ac7263c26353af.png") %>
    </div>  
    <div class="navbar-collapse collapse">
      <ul class"nav navbar-nav navbar-right">
        <li>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete, class:"btn btn-default") %>        
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="main-bar">
  <div class="container">
    <h4 class="glyphicon glyphicon-home page-title text-center"> Content tool &#47; Stats for this account</h4>
  </div>
</div>
<div class="panel panel-default">
  <div class="panel-body">
    <div class="total pull-left">
      <div class="panel panel-info">
        <div class="panel-heading text-center">
          <strong>Games available</strong>
        </div>
        <div class="panel-body text-center align-center">
          <%= @total_games %>
        </div>
      </div>
    </div>
    <div class="total pull-left">
      <div class="panel panel-info">
        <div class="panel-heading text-center">
          <strong>Games without promo text</strong>
        </div>
        <div class="panel-body text-center align-center">
          <%= (@total_games_without_promo/@total_games).round(3)*100 %> %
        </div>
      </div>
    </div>
    <div class="total pull-left">
      <div class="panel panel-info">
        <div class="panel-heading text-center">
          <strong>Games without 300x250 creatives</strong>
        </div>
        <div class="panel-body text-center align-center">
          <%= (@total_games_without_square_banners/@total_games).round(2)*100 %> %
        </div>
      </div>
    </div>
    <div class="total pull-left">
      <div class="panel panel-info">
        <div class="panel-heading text-center">
          <strong>Games wthout 320x50 creatives</strong>
        </div>
        <div class="panel-body text-center align-center">
          <%= (@total_games_without_flat_banners/@total_games).round(3)*100 %> %
        </div>
      </div>
    </div>
    <div class="total pull-left">
      <div class="panel panel-info">
        <div class="panel-heading text-center">
          <strong>Games without video in the requested language</strong>
        </div>
        <div class="panel-body text-center align-center">
          <%= (@total_games_without_video/@total_games).round(3)*100 %> %
        </div>
      </div>
    </div>
  </div>
</div>

<div class="main-page">
  <div class="row-fluid">
    <div class="span12">
      <%= render partial:  'grid' %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContentTool</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>